groups:
- heading: Journal Reviewer
  items:
  - ACM Computing Surveys
  - Transactions on Machine Learning Research
- heading: Conference Reviewer
  items:
  - Conference on Neural Information Processing Systems, 2026
  - International Conference on Machine Learning, 2026
  - International Conference on Learning Representations, 2026
  - AI4MATH Workshop at International Conference on Machine Learning, 2025
