name: Update Google Scholar Stats

on:
  schedule:
    # Run daily at midnight UTC
    - cron: '0 0 * * *'
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-scholar:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    permissions:
      contents: write

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        ref: main
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r google_scholar_crawler/requirements.txt

    - name: Run Google Scholar crawler
      timeout-minutes: 5
      continue-on-error: true
      run: |
        python google_scholar_crawler/update_scholar.py || echo "Crawler failed, will retry next time"

    - name: Check if data was fetched
      id: check_data
      run: |
        if [ -f "google-scholar-stats/gs_data.json" ]; then
          echo "data_exists=true" >> $GITHUB_OUTPUT
          echo "Data file found, contents:"
          cat google-scholar-stats/gs_data.json
        else
          echo "data_exists=false" >> $GITHUB_OUTPUT
          echo "Data file not found"
        fi

    - name: Push to google-scholar-stats branch
      if: steps.check_data.outputs.data_exists == 'true'
      run: |
        cd google-scholar-stats
        git init
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *.json
        git commit -m "Update Google Scholar stats - $(date '+%Y-%m-%d')"
        # Create the branch if it doesn't exist
        git branch -M google-scholar-stats
        git remote add origin https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        git push --force origin google-scholar-stats
